# Generated by Django 5.2.7 on 2025-10-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="middle_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
