# Generated by Django 6.0 on 2026-03-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_clientapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientapplication",
            name="delivery",
            field=models.CharField(default="delivery", max_length=20),
        ),
        migrations.AddField(
            model_name="clientapplication",
            name="payment_method",
            field=models.CharField(default="card", max_length=20),
        ),
        migrations.AddField(
            model_name="clientapplication",
            name="reservation",
            field=models.CharField(default="no", max_length=5),
        ),
        migrations.AddField(
            model_name="clientapplication",
            name="reservation_days",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
