# Generated by Django 6.0 on 2026-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_clientapplication_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На рассмотрении"),
                    ("accepted", "Принят"),
                    ("canceled", "Отменено"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
