# Generated by Django 6.0 on 2026-03-24 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_clientapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "На рассмотрении"),
                    ("accepted", "Принят"),
                    ("canceled", "Отменено"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("diagnostic", "Диагностика"),
                            ("maintenance", "Техническое обслуживание"),
                            ("repair", "Ремонт"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "На рассмотрении"),
                            ("accepted", "Принят"),
                            ("canceled", "Отменено"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "time")},
            },
        ),
    ]
