# Generated by Django 6.0 on 2026-03-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_clientapplication_status_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="brand",
            field=models.CharField(default="brand", max_length=100),
        ),
        migrations.AddField(
            model_name="appointment",
            name="year",
            field=models.PositiveIntegerField(default="0"),
        ),
    ]
