# Generated by Django 6.0 on 2026-04-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_appointment_brand_appointment_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=500, unique=True)),
            ],
            options={
                "db_table": "parts",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(max_length=50),
        ),
    ]
