# Generated by Django 6.0 on 2026-04-22 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_part_alter_appointment_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientapplication",
            name="detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="account.part",
            ),
        ),
    ]
