# МАРКИ АВТОМОБИЛЯ
CAR_BRANDS = ["AITO", "Arcfox", "Avita", "Arrinera", "Artega", "Ascari", "Asia", "Askam", "Aston Martin",
              "Atalanta Motors", "Auburn", "Audi", "Aurus", "Austin", "Austin Healey", "Autobacs Seven", "Autobianchi",
              "Axon Automotive", "ARO", "Abarth", "Abbott-Detroit", "ABT", "AC Cars", "Acura", "Adler", "Agrale",
              "Aiways", "Aixam", "Alfa Romeo", "Alpina", "Alpine", "Alta", "Alvis", "American Motors (AMC)", "AMG",
              "Apollo", "Arash", "Ariel", "Автокам", "Abadal", "Bisu", "Beijing Auto", "BAIC New Energy", "BAW",
              "BAIC Huansu", "BAIC Weiwang", "Bugatti", "Buick", "BYD", "Byvin", "Batmobile", "Bentley", "Berkeley",
              "Berliet", "Bertone", "BharatBenz", "Bilenkin", "Bio auto", "Bitter", "Bizzarrini", "BMW", "BMW M",
              "Borgward", "Bowler", "Brabus", "Brammo", "Brilliance", "Bristol Cars", "Brooke Cars", "Bufori", "BAC",
              "BAIC Motor", "Bajaj", "Baltijas Džips", "Baojun", "Бронто", "Chenggong", "CHTC", "Cizeta", "Coggiola",
              "Cole", "Cord", "Corre La Licorne", "Corvette", "Chana", "Changan", "Changfeng", "Changhe", "Chery",
              "Chevrolet", "Chrysler", "Cisitalia", "Citroën", "Citroën DS", "Cadillac", "Callaway", "Caparo",
              "Carbodies", "Carlsson", "Caterham", "Dorcen", "Denza", "Detroit Electric", "Devel Motors", "Diatto",
              "DINA", "DKW", "Dodge", "Dongfeng", "Donkervoort", "Drive eO", "Daihatsu", "Daimler", "Dallara", "Dartz",
              "Datsun", "De Tomaso", "Delage", "DeLorean (DMC)", "Derways", "DeSoto", "Dacia", "Dadi", "Daewoo", "DAF",
              "Enoreve", "Everus", "Evolute", "Exeed", "EDAG", "Edsel", "Eicher", "Elfin Sportcars", "Elva", "Englon",
              "ERF Trucks", "Eterniti Motors", "Excalibur", "Eagle", "Ё-Авто", "Feifan", "Foday", "Freightliner Trucks",
              "FSO", "Fuqi", "Faraday Future", "FAW", "Ferrari", "Fiat", "Fisker", "Foden Trucks", "Force Motors",
              "Ford", "Ford Performance Vehicles (FPV)", "Foton", "Facel Vega", "Guojin Jun Xing", "Golden Dragon",
              "Gumpert", "Ginetta", "GMC", "Gonow", "Gordon", "Great Wall", "Grinnall Cars", "GTA Motor (Spania GTA)",
              "GAC Group", "Gardner Douglas", "Geely", "General Motors (GM)", "Genesis", "Geo", "Gillet", "ГАЗ",
              "Higer", "Horki", "Huasong", "Hycan", "Hanteng", "Hongqi", "Holden Special Vehicles (HSV)", "Hommell",
              "Honda", "Horch", "HuangHai", "Hudson", "Hummer", "Hupmobile", "Hyundai", "Hanomag", "Haval", "Hawtai",
              "Heinkel", "Hennessey", "Hillman", "Hindustan Motors", "Hino", "Hispano-Suiza", "Holden", "Hafei",
              "Haima", "Iveco", "Infiniti", "Innocenti", "Intermeccanica", "International Harvester",
              "International Trucks", "Iran Khodro", "Irizar", "Isdera", "Iso Rivolta", "Isuzu", "IC Bus", "ИЖ",
              "Jetour", "Jonway", "JAC", "Jaguar", "Jawa", "JBA Motors", "Jeep", "Jensen", "Jinbei", "JMC (Jiangling)",
              "Kawei", "Karry", "Kandi", "Kaiyi", "Karma", "Keating Supercars", "Kenworth", "Kia Motors", "Koenigsegg",
              "KTM", "Kaiser", "КамАЗ", "Канонир", "Комбат", "LeEco", "Link Tour", "Leap Motor", "LuxGen", "Lynk&Co",
              "Lingbao", "Lobini", "London EV Company", "Lotus", "LTI (London Taxis International)", "Lucid Motors",
              "Landwind", "Laraki", "Lexus", "Leyland", "Li Auto", "Lifan", "Ligier", "Lincoln", "Lister", "Lloyd",
              "Lagonda", "Lamborghini", "Lancia", "Land Rover", "Лада", "ЛуАЗ", "Maple", "Mini", "Mitsubishi",
              "Mitsuoka", "MK Sportscars", "Monteverdi", "Morgan", "Morris", "Mosler", "Mustang", "McLaren", "Mega",
              "Melkus", "Mercedes-Benz", "Mercury", "Merkur", "Metrocab", "MG", "Microcar", "Mills Extreme Vehicles",
              "Marcos", "Marlin", "Marussia", "Maruti", "Maserati", "Mastretta", "Maxus", "Maybach", "Mazda",
              "Mazzanti Automobili", "Mack Trucks", "Mahindra", "MAN", "Mansory", "МАЗ", "Москвич", "Neta",
              "Navistar International", "Nio", "Nismo", "Nissan", "Nissan GT-R", "Noble", "Nash", "Ora", "OMODA",
              "Oullim Motors", "Oldsmobile", "Oltcit", "Opel", "OSCA", "Polarsun", "Prodrive", "Proton", "PUCH",
              "Polestar", "Pontiac", "Porsche", "Praga", "Premier Automotive Group", "PGO", "Piaggio", "Pierce-Arrow",
              "Pininfarina", "Plymouth", "Paccar", "Packard", "Pagani", "Panhard", "Panoz", "Pegaso", "Perodua",
              "Peterbilt", "Peugeot", "Qiteng", "Qoros", "Qvale", "Rely", "Riich", "Ruichi", "Rover", "Ruf", "Renault",
              "Renault Samsung", "Rezvani", "Riley", "Rimac", "Rinspeed", "Roewe", "Rolls-Royce", "Ronart Cars",
              "Rossion Automotive", "Radical Sportscars", "Ram Trucks", "Rambler", "Ranz", "Ravon", "Skylark", "Sunra",
              "Sitech", "Sollers", "Sinotruk VGV", "Sehol", "Skyworth", "Seres", "SAIC", "Soueast", "Spyker",
              "SsangYong", "SSC North America", "Sterling Trucks", "Steyr", "Studebaker", "Subaru", "Suffolk Sportcars",
              "Suzuki", "SEAT", "Setra", "Shanghai Maple", "Shelby Mustang", "ShuangHuan", "Simca", "Singer",
              "Sisu Auto", "Škoda", "Smart", "Saab", "SAIC Motor", "SAIPA", "Saleen", "Santana", "Saturn", "Scania",
              "Scion", "СМЗ", "Traum", "Tianma", "Tank", "Toroidion", "Toyota", "Toyota Crown", "Trabant", "Tramontana",
              "Trion", "Triumph", "Troller", "TVR", "Talbot", "Tata", "Tatra", "Tauro Sport Auto", "Tazzari", "TechArt",
              "Tesla", "Thai Rung", "Tianye", "Tofas", "ТагАЗ", "Ultima Sports", "UD Trucks", "Voyah", "Vandenbrink",
              "Vauxhall", "Vector Motors", "Vencer", "Venturi", "Venucia", "Volkswagen", "Volvo", "Vortex", "WM Motor",
              "Wey", "Weichai", "W Motors", "Wanderer", "Wartburg", "Western Star", "Westfield", "Wiesmann", "Willys",
              "Willys-Overland", "Wuling", "XPeng", "Xin Kai", "Youngman Lotus", "Yudo", "Yema", "Yulon", "ZEEKR",
              "Zinoro", "Zhi Dou", "Zedriv", "Zhiji (IM Motors)", "Zarooq Motors", "Zastava", "Zenos Cars",
              "Zenvo Automotive", "Zibar", "Zotye", "ZX", "ЗАЗ", "ЗИЛ", "ЗиС", "УАЗ"]

